server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route 1: Auth Service
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        # Route 2: Catalog Service
        - id: catalog-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/destinations/**, /api/packages/**

        # Route 3: Booking Service
        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/bookings/**, /api/payments/**

        # Route 4: Feedback Service
        - id: feedback-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/reviews/**